//import { Inter } from "next/font/google";
import { Caveat } from "next/font/google";
//import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });
const caveat = Caveat({ subsets: ["latin"],weight: "700" });

export const metadata = {
  title: "Recipe App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={/*inter.className*/caveat.className}>{children}</body>
    </html>
  );
}
